spring:
  application:
    name: spring-boot-project

  # MySQL 설정
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    url: jdbc:mysql://localhost:3306/springbook
#    username: spring
#    password: book
#    driver-class-name: com.mysql.cj.jdbc.Driver
  # H2 설정 (테스트용, 필요시 활성화-위에꺼 주석해야함)

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create  # 데이터베이스 초기화 전략(none, create, create-drop, update, validate)
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # 콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
        show_sql: true    # 실행되는 쿼리 콘솔 출력

  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: jcdoom@naver.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Swagger 설정
springdoc:
  api-docs:
    enabled: false
  default-consume-media-type: application/json
  default-produce-media-type: application/json
  swagger-ui:
    enabled: false
    path: /swagger-ui.html       # 접속 경로 변경
    groups-order: DESC           # 그룹 정렬 순서
    operations-sorter: METHOD    # HTTP 메서드순 정렬
    tags-sorter: ALPHA         # 태그 정렬이 필요하다면 추가