spring:
  application:
    name: spring-of-toby-boot

  # MySQL 설정
  datasource:
    url: jdbc:mysql://localhost:3306/springbook
    username: spring
    password: book
    driver-class-name: com.mysql.cj.jdbc.Driver
  # H2 설정 (테스트용, 필요시 활성화-위에꺼 주석해야함)
  #    url: jdbc:h2:mem:testdb
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console